### PR TITLE
How to spin it up

### LINKED ISSUE #2: Combine with nacho?
[Nacho](https://github.com/mapbox/nacho) was my original foray into watchbot, but that was prior to ecs-watchbot. Converting that into ecs-watchbot would make it the same thing as this repository. I'd be happy to write up a little "how to spin this up" in the readme, like Nacho.

Can we join forces? It's always [better when we're together](https://www.youtube.com/watch?v=u57d4_b_YgI). 

@rclark @jakepruitt

### PR DESCRIPTION
**Pull request by mapsam**
Adds "how to spin it up" section to the README and updates to @mapbox/cloudfriend 

resolves #2 

cc @rclark

### CODE REVIEW

**Comment by rclark** [comment]
This repo is public -- can we change the directions to use [cfn-config](https://github.com/mapbox/cfn-config) instead of mbxcli?

**Comment by mapsam** [comment]
@rclark yep I can do that - how do you suggest viewing logs? Just through the UI task by task?

**Comment by rclark** [comment]
Yeah, UI is probably the most common / straightforward approach?

**Comment by mapsam** [comment]
@rclark great- updated the README with cfn-config (good catch 😅 )

**Comment by rclark** [comment]
Thanks @mapsam!

**Comment by mapsam** [comment]
Here we go!

**Pull request merged**
